[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting = "9UKZFA4opT5zYuq5SidXdeLLMpxGMtGMybYMJfL2LyKZ"

[provider]
cluster = "devnet"
#url = "https://solana-devnet.infura.io/v3/70ec61545bb04231a5b51068bb7c330f"
wallet = "./bosiRUeLUGZ4d8Cc38WpsC54eHJbc22946EVq9sdTqN.json"


[scripts]
test = "cargo test"

[hooks]
